/* Generated by Rafters - DO NOT EDIT */

export const tokens = {
  breakpoint: {
    /** Small screens - landscape phones, small tablets */
    'breakpoint-sm': '640px',
    /** Media query for sm breakpoint */
    'screen-sm': '(min-width: 640px)',
    /** Medium screens - tablets, small laptops */
    'breakpoint-md': '768px',
    /** Media query for md breakpoint */
    'screen-md': '(min-width: 768px)',
    /** Large screens - laptops, small desktops */
    'breakpoint-lg': '1024px',
    /** Media query for lg breakpoint */
    'screen-lg': '(min-width: 1024px)',
    /** Extra large screens - desktops */
    'breakpoint-xl': '1280px',
    /** Media query for xl breakpoint */
    'screen-xl': '(min-width: 1280px)',
    /** Extra extra large screens - large desktops, monitors */
    'breakpoint-2xl': '1536px',
    /** Media query for 2xl breakpoint */
    'screen-2xl': '(min-width: 1536px)',
    /** Smallest container (256px) - icons, badges */
    'container-3xs': '16rem',
    /** Extra extra small (288px) - compact cards */
    'container-2xs': '18rem',
    /** Extra small (320px) - mobile-width cards */
    'container-xs': '20rem',
    /** Small (384px) - standard cards */
    'container-sm': '24rem',
    /** Medium (448px) - wide cards, panels */
    'container-md': '28rem',
    /** Large (512px) - sidebars, dialog content */
    'container-lg': '32rem',
    /** Extra large (576px) - main content panels */
    'container-xl': '36rem',
    /** 2XL (672px) - wide content areas */
    'container-2xl': '42rem',
    /** 3XL (768px) - tablet-width containers */
    'container-3xl': '48rem',
    /** 4XL (896px) - wide panels */
    'container-4xl': '56rem',
    /** 5XL (1024px) - desktop content */
    'container-5xl': '64rem',
    /** 6XL (1152px) - wide desktop content */
    'container-6xl': '72rem',
    /** 7XL (1280px) - maximum content width */
    'container-7xl': '80rem',
    /** Maximum width before sm breakpoint */
    'breakpoint-sm-max': '639px',
    /** Maximum width before md breakpoint */
    'breakpoint-md-max': '767px',
    /** Maximum width before lg breakpoint */
    'breakpoint-lg-max': '1023px',
    /** Maximum width before xl breakpoint */
    'breakpoint-xl-max': '1279px',
    /** Maximum width before 2xl breakpoint */
    'breakpoint-2xl-max': '1535px',
    /** Media query for reduced motion preference */
    'breakpoint-motion-reduce': '(prefers-reduced-motion: reduce)',
    /** Media query for dark mode preference */
    'breakpoint-dark': '(prefers-color-scheme: dark)',
    /** Media query for high contrast preference */
    'breakpoint-high-contrast': '(prefers-contrast: more)',
    /** Media query for forced colors mode (Windows High Contrast) */
    'breakpoint-forced-colors': '(forced-colors: active)',
    /** Breakpoint scale reference */
    'breakpoint-scale': {"viewport":{"sm":640,"md":768,"lg":1024,"xl":1280,"2xl":1536},"container":{"3xs":"16rem","2xs":"18rem","xs":"20rem","sm":"24rem","md":"28rem","lg":"32rem","xl":"36rem","2xl":"42rem","3xl":"48rem","4xl":"56rem","5xl":"64rem","6xl":"72rem","7xl":"80rem"},"note":"Container queries use --container-* theme variables with rem values. Use @xs:, @sm:, @md:, etc. variants."},
  },
  color: {
    /** neutral shade at 50 level - light background range */
    'neutral-50': 'oklch(0.985 0 0)',
    /** neutral shade at 100 level - light background range */
    'neutral-100': 'oklch(0.967 0 0)',
    /** neutral shade at 200 level - light background range */
    'neutral-200': 'oklch(0.92 0 0)',
    /** neutral shade at 300 level - light background range */
    'neutral-300': 'oklch(0.869 0 0)',
    /** neutral shade at 400 level - mid-tone for borders and secondary text */
    'neutral-400': 'oklch(0.707 0 0)',
    /** neutral shade at 500 level - mid-tone for borders and secondary text */
    'neutral-500': 'oklch(0.552 0 0)',
    /** neutral shade at 600 level - mid-tone for borders and secondary text */
    'neutral-600': 'oklch(0.442 0 0)',
    /** neutral shade at 700 level - dark foreground range */
    'neutral-700': 'oklch(0.37 0 0)',
    /** neutral shade at 800 level - dark foreground range */
    'neutral-800': 'oklch(0.269 0 0)',
    /** neutral shade at 900 level - dark foreground range */
    'neutral-900': 'oklch(0.2 0 0)',
    /** neutral shade at 950 level - dark foreground range */
    'neutral-950': 'oklch(0.141 0 0)',
    /** Complete neutral color family with 11-position scale */
    'neutral': 'oklch(0.552 0.000 0.0)',
    /** silver-true-glacier shade at 50 level - light background range */
    'silver-true-glacier-50': 'oklch(0.95 0.036 180)',
    /** silver-true-glacier shade at 100 level - light background range */
    'silver-true-glacier-100': 'oklch(0.896 0.12 180)',
    /** silver-true-glacier shade at 200 level - light background range */
    'silver-true-glacier-200': 'oklch(0.839 0.12 180)',
    /** silver-true-glacier shade at 300 level - light background range */
    'silver-true-glacier-300': 'oklch(0.78 0.12 180)',
    /** silver-true-glacier shade at 400 level - mid-tone for borders and secondary text */
    'silver-true-glacier-400': 'oklch(0.716 0.12 180)',
    /** silver-true-glacier shade at 500 level - mid-tone for borders and secondary text */
    'silver-true-glacier-500': 'oklch(0.645 0.12 180)',
    /** silver-true-glacier shade at 600 level - mid-tone for borders and secondary text */
    'silver-true-glacier-600': 'oklch(0.55 0.12 180)',
    /** silver-true-glacier shade at 700 level - dark foreground range */
    'silver-true-glacier-700': 'oklch(0.425 0.12 180)',
    /** silver-true-glacier shade at 800 level - dark foreground range */
    'silver-true-glacier-800': 'oklch(0.3 0.12 180)',
    /** silver-true-glacier shade at 900 level - dark foreground range */
    'silver-true-glacier-900': 'oklch(0.175 0.12 180)',
    /** silver-true-glacier shade at 950 level - dark foreground range */
    'silver-true-glacier-950': 'oklch(0.05 0.072 180)',
    /** Complete silver-true-glacier color family with 11-position scale */
    'silver-true-glacier': 'oklch(0.645 0.120 180.0)',
    /** silver-bold-fire-truck shade at 50 level - light background range */
    'silver-bold-fire-truck-50': 'oklch(0.95 0.06 0)',
    /** silver-bold-fire-truck shade at 100 level - light background range */
    'silver-bold-fire-truck-100': 'oklch(0.896 0.2 0)',
    /** silver-bold-fire-truck shade at 200 level - light background range */
    'silver-bold-fire-truck-200': 'oklch(0.839 0.2 0)',
    /** silver-bold-fire-truck shade at 300 level - light background range */
    'silver-bold-fire-truck-300': 'oklch(0.78 0.2 0)',
    /** silver-bold-fire-truck shade at 400 level - mid-tone for borders and secondary text */
    'silver-bold-fire-truck-400': 'oklch(0.716 0.2 0)',
    /** silver-bold-fire-truck shade at 500 level - mid-tone for borders and secondary text */
    'silver-bold-fire-truck-500': 'oklch(0.645 0.2 0)',
    /** silver-bold-fire-truck shade at 600 level - mid-tone for borders and secondary text */
    'silver-bold-fire-truck-600': 'oklch(0.55 0.2 0)',
    /** silver-bold-fire-truck shade at 700 level - dark foreground range */
    'silver-bold-fire-truck-700': 'oklch(0.425 0.2 0)',
    /** silver-bold-fire-truck shade at 800 level - dark foreground range */
    'silver-bold-fire-truck-800': 'oklch(0.3 0.2 0)',
    /** silver-bold-fire-truck shade at 900 level - dark foreground range */
    'silver-bold-fire-truck-900': 'oklch(0.175 0.2 0)',
    /** silver-bold-fire-truck shade at 950 level - dark foreground range */
    'silver-bold-fire-truck-950': 'oklch(0.05 0.12 0)',
    /** Complete silver-bold-fire-truck color family with 11-position scale */
    'silver-bold-fire-truck': 'oklch(0.645 0.200 0.0)',
    /** silver-true-honey shade at 50 level - light background range */
    'silver-true-honey-50': 'oklch(0.95 0.036 60)',
    /** silver-true-honey shade at 100 level - light background range */
    'silver-true-honey-100': 'oklch(0.896 0.12 60)',
    /** silver-true-honey shade at 200 level - light background range */
    'silver-true-honey-200': 'oklch(0.839 0.12 60)',
    /** silver-true-honey shade at 300 level - light background range */
    'silver-true-honey-300': 'oklch(0.78 0.12 60)',
    /** silver-true-honey shade at 400 level - mid-tone for borders and secondary text */
    'silver-true-honey-400': 'oklch(0.716 0.12 60)',
    /** silver-true-honey shade at 500 level - mid-tone for borders and secondary text */
    'silver-true-honey-500': 'oklch(0.645 0.12 60)',
    /** silver-true-honey shade at 600 level - mid-tone for borders and secondary text */
    'silver-true-honey-600': 'oklch(0.55 0.12 60)',
    /** silver-true-honey shade at 700 level - dark foreground range */
    'silver-true-honey-700': 'oklch(0.425 0.12 60)',
    /** silver-true-honey shade at 800 level - dark foreground range */
    'silver-true-honey-800': 'oklch(0.3 0.12 60)',
    /** silver-true-honey shade at 900 level - dark foreground range */
    'silver-true-honey-900': 'oklch(0.175 0.12 60)',
    /** silver-true-honey shade at 950 level - dark foreground range */
    'silver-true-honey-950': 'oklch(0.05 0.072 60)',
    /** Complete silver-true-honey color family with 11-position scale */
    'silver-true-honey': 'oklch(0.645 0.120 60.0)',
    /** silver-true-citrine shade at 50 level - light background range */
    'silver-true-citrine-50': 'oklch(0.95 0.036 90)',
    /** silver-true-citrine shade at 100 level - light background range */
    'silver-true-citrine-100': 'oklch(0.896 0.12 90)',
    /** silver-true-citrine shade at 200 level - light background range */
    'silver-true-citrine-200': 'oklch(0.839 0.12 90)',
    /** silver-true-citrine shade at 300 level - light background range */
    'silver-true-citrine-300': 'oklch(0.78 0.12 90)',
    /** silver-true-citrine shade at 400 level - mid-tone for borders and secondary text */
    'silver-true-citrine-400': 'oklch(0.716 0.12 90)',
    /** silver-true-citrine shade at 500 level - mid-tone for borders and secondary text */
    'silver-true-citrine-500': 'oklch(0.645 0.12 90)',
    /** silver-true-citrine shade at 600 level - mid-tone for borders and secondary text */
    'silver-true-citrine-600': 'oklch(0.55 0.12 90)',
    /** silver-true-citrine shade at 700 level - dark foreground range */
    'silver-true-citrine-700': 'oklch(0.425 0.12 90)',
    /** silver-true-citrine shade at 800 level - dark foreground range */
    'silver-true-citrine-800': 'oklch(0.3 0.12 90)',
    /** silver-true-citrine shade at 900 level - dark foreground range */
    'silver-true-citrine-900': 'oklch(0.175 0.12 90)',
    /** silver-true-citrine shade at 950 level - dark foreground range */
    'silver-true-citrine-950': 'oklch(0.05 0.072 90)',
    /** Complete silver-true-citrine color family with 11-position scale */
    'silver-true-citrine': 'oklch(0.645 0.120 90.0)',
    /** silver-true-sky shade at 50 level - light background range */
    'silver-true-sky-50': 'oklch(0.95 0.036 210)',
    /** silver-true-sky shade at 100 level - light background range */
    'silver-true-sky-100': 'oklch(0.896 0.12 210)',
    /** silver-true-sky shade at 200 level - light background range */
    'silver-true-sky-200': 'oklch(0.839 0.12 210)',
    /** silver-true-sky shade at 300 level - light background range */
    'silver-true-sky-300': 'oklch(0.78 0.12 210)',
    /** silver-true-sky shade at 400 level - mid-tone for borders and secondary text */
    'silver-true-sky-400': 'oklch(0.716 0.12 210)',
    /** silver-true-sky shade at 500 level - mid-tone for borders and secondary text */
    'silver-true-sky-500': 'oklch(0.645 0.12 210)',
    /** silver-true-sky shade at 600 level - mid-tone for borders and secondary text */
    'silver-true-sky-600': 'oklch(0.55 0.12 210)',
    /** silver-true-sky shade at 700 level - dark foreground range */
    'silver-true-sky-700': 'oklch(0.425 0.12 210)',
    /** silver-true-sky shade at 800 level - dark foreground range */
    'silver-true-sky-800': 'oklch(0.3 0.12 210)',
    /** silver-true-sky shade at 900 level - dark foreground range */
    'silver-true-sky-900': 'oklch(0.175 0.12 210)',
    /** silver-true-sky shade at 950 level - dark foreground range */
    'silver-true-sky-950': 'oklch(0.05 0.072 210)',
    /** Complete silver-true-sky color family with 11-position scale */
    'silver-true-sky': 'oklch(0.645 0.120 210.0)',
    /** silver-true-violet shade at 50 level - light background range */
    'silver-true-violet-50': 'oklch(0.95 0.036 270)',
    /** silver-true-violet shade at 100 level - light background range */
    'silver-true-violet-100': 'oklch(0.896 0.12 270)',
    /** silver-true-violet shade at 200 level - light background range */
    'silver-true-violet-200': 'oklch(0.839 0.12 270)',
    /** silver-true-violet shade at 300 level - light background range */
    'silver-true-violet-300': 'oklch(0.78 0.12 270)',
    /** silver-true-violet shade at 400 level - mid-tone for borders and secondary text */
    'silver-true-violet-400': 'oklch(0.716 0.12 270)',
    /** silver-true-violet shade at 500 level - mid-tone for borders and secondary text */
    'silver-true-violet-500': 'oklch(0.645 0.12 270)',
    /** silver-true-violet shade at 600 level - mid-tone for borders and secondary text */
    'silver-true-violet-600': 'oklch(0.55 0.12 270)',
    /** silver-true-violet shade at 700 level - dark foreground range */
    'silver-true-violet-700': 'oklch(0.425 0.12 270)',
    /** silver-true-violet shade at 800 level - dark foreground range */
    'silver-true-violet-800': 'oklch(0.3 0.12 270)',
    /** silver-true-violet shade at 900 level - dark foreground range */
    'silver-true-violet-900': 'oklch(0.175 0.12 270)',
    /** silver-true-violet shade at 950 level - dark foreground range */
    'silver-true-violet-950': 'oklch(0.05 0.072 270)',
    /** Complete silver-true-violet color family with 11-position scale */
    'silver-true-violet': 'oklch(0.645 0.120 270.0)',
  },
  depth: {
    /** Base layer - document flow elements */
    'depth-base': '0',
    /** Dropdown menus and select options */
    'depth-dropdown': '10',
    /** Sticky elements - headers, toolbars */
    'depth-sticky': '20',
    /** Navigation panels - sidebars, slide-out nav */
    'depth-navigation': '25',
    /** Fixed elements - always visible */
    'depth-fixed': '30',
    /** Modal dialogs - blocking overlays */
    'depth-modal': '40',
    /** Popovers above modals */
    'depth-popover': '50',
    /** Tooltips - highest common layer */
    'depth-tooltip': '60',
    /** Overlay backdrops - screen-dimming layers behind modals */
    'depth-overlay': '70',
    /** Below base layer - backgrounds, decorative elements */
    'depth-below': '-1',
    /** Maximum layer - emergency overlay (e.g., dev tools) */
    'depth-max': '9999',
    /** Depth scale reference */
    'depth-scale': {"gap":10,"note":"Each level has 10-unit gaps for intermediate values","levels":{"base":0,"dropdown":10,"sticky":20,"navigation":25,"fixed":30,"modal":40,"popover":50,"tooltip":60,"overlay":70}},
  },
  elevation: {
    /** Surface level - flat, in-flow elements */
    'elevation-surface': {"depth":"var(--depth-base)","shadow":"var(--shadow-none)"},
    /** Z-index component of surface elevation */
    'elevation-surface-z': 'var(--depth-base)',
    /** Shadow component of surface elevation */
    'elevation-surface-shadow': 'var(--shadow-none)',
    /** Slightly raised - subtle depth without z-index change */
    'elevation-raised': {"depth":"var(--depth-base)","shadow":"var(--shadow-sm)"},
    /** Z-index component of raised elevation */
    'elevation-raised-z': 'var(--depth-base)',
    /** Shadow component of raised elevation */
    'elevation-raised-shadow': 'var(--shadow-sm)',
    /** Overlay level - dropdowns and menus */
    'elevation-overlay': {"depth":"var(--depth-dropdown)","shadow":"var(--shadow)"},
    /** Z-index component of overlay elevation */
    'elevation-overlay-z': 'var(--depth-dropdown)',
    /** Shadow component of overlay elevation */
    'elevation-overlay-shadow': 'var(--shadow)',
    /** Sticky level - persistent navigation */
    'elevation-sticky': {"depth":"var(--depth-sticky)","shadow":"var(--shadow-md)"},
    /** Z-index component of sticky elevation */
    'elevation-sticky-z': 'var(--depth-sticky)',
    /** Shadow component of sticky elevation */
    'elevation-sticky-shadow': 'var(--shadow-md)',
    /** Modal level - blocking dialogs */
    'elevation-modal': {"depth":"var(--depth-modal)","shadow":"var(--shadow-lg)"},
    /** Z-index component of modal elevation */
    'elevation-modal-z': 'var(--depth-modal)',
    /** Shadow component of modal elevation */
    'elevation-modal-shadow': 'var(--shadow-lg)',
    /** Popover level - above modals */
    'elevation-popover': {"depth":"var(--depth-popover)","shadow":"var(--shadow-xl)"},
    /** Z-index component of popover elevation */
    'elevation-popover-z': 'var(--depth-popover)',
    /** Shadow component of popover elevation */
    'elevation-popover-shadow': 'var(--shadow-xl)',
    /** Tooltip level - highest common UI */
    'elevation-tooltip': {"depth":"var(--depth-tooltip)","shadow":"var(--shadow-lg)"},
    /** Z-index component of tooltip elevation */
    'elevation-tooltip-z': 'var(--depth-tooltip)',
    /** Shadow component of tooltip elevation */
    'elevation-tooltip-shadow': 'var(--shadow-lg)',
    /** Elevation scale reference */
    'elevation-scale': {"levels":{"surface":{"depth":"depth-base","shadow":"shadow-none"},"raised":{"depth":"depth-base","shadow":"shadow-sm"},"overlay":{"depth":"depth-dropdown","shadow":"shadow"},"sticky":{"depth":"depth-sticky","shadow":"shadow-md"},"modal":{"depth":"depth-modal","shadow":"shadow-lg"},"popover":{"depth":"depth-popover","shadow":"shadow-xl"},"tooltip":{"depth":"depth-tooltip","shadow":"shadow-lg"}},"note":"Each elevation level pairs z-index with appropriate shadow"},
  },
  focus: {
    /** Default focus ring width - WCAG 2.2 requires minimum 2px */
    'focus-ring-width': '0.125rem',
    /** Focus ring color - inherits from semantic ring token */
    'focus-ring-color': 'var(--ring)',
    /** Default focus ring - suitable for most interactive elements */
    'focus-ring': {"width":"0.125rem","offset":"0.125rem","style":"solid","color":"var(--ring)"},
    /** CSS outline shorthand for default focus ring */
    'focus-outline': '0.125rem solid var(--ring)',
    /** Focus ring offset for default style */
    'focus-offset': '0.125rem',
    /** Inset focus ring - for elements where external ring would be cut off */
    'focus-ring-inset': {"width":"0.125rem","offset":"-0.125rem","style":"solid","color":"var(--ring)"},
    /** CSS outline shorthand for inset focus ring */
    'focus-outline-inset': '0.125rem solid var(--ring)',
    /** Focus ring offset for inset style */
    'focus-offset-inset': '-0.125rem',
    /** Thick focus ring - for high-visibility needs */
    'focus-ring-thick': {"width":"0.188rem","offset":"0.125rem","style":"solid","color":"var(--ring)"},
    /** CSS outline shorthand for thick focus ring */
    'focus-outline-thick': '0.188rem solid var(--ring)',
    /** Focus ring offset for thick style */
    'focus-offset-thick': '0.125rem',
    /** Subtle focus ring - for dense UIs with many focusable elements */
    'focus-ring-subtle': {"width":"0.063rem","offset":"0.125rem","style":"solid","color":"var(--ring)"},
    /** CSS outline shorthand for subtle focus ring */
    'focus-outline-subtle': '0.063rem solid var(--ring)',
    /** Focus ring offset for subtle style */
    'focus-offset-subtle': '0.125rem',
    /** Focus ring for containers with focused descendants */
    'focus-within-ring': {"width":"0.125rem","offset":"0","style":"solid","color":"var(--ring)"},
    /** Focus ring for Windows High Contrast Mode */
    'focus-high-contrast': {"width":"0.188rem","offset":"0.125rem","style":"solid","color":"Highlight"},
  },
  motion: {
    /** Base transition duration - all motion timing derives from this */
    'motion-duration-base': '150ms',
    /** Instant - no animation */
    'motion-duration-instant': '0ms',
    /** Fast - micro-interactions, hover states */
    'motion-duration-fast': '125ms',
    /** Normal - standard UI transitions */
    'motion-duration-normal': '150ms',
    /** Slow - enter/exit animations */
    'motion-duration-slow': '180ms',
    /** Slower - emphasis, large element transitions */
    'motion-duration-slower': '216ms',
    /** Linear - constant speed, mechanical feel */
    'motion-easing-linear': 'linear',
    /** Ease in - starts slow, accelerates (exiting) */
    'motion-easing-ease-in': 'cubic-bezier(0.42, 0, 1, 1)',
    /** Ease out - starts fast, decelerates (entering) */
    'motion-easing-ease-out': 'cubic-bezier(0, 0, 0.58, 1)',
    /** Ease in-out - symmetric acceleration/deceleration */
    'motion-easing-ease-in-out': 'cubic-bezier(0.42, 0, 0.58, 1)',
    /** Productive - quick, efficient, minimal overshoot */
    'motion-easing-productive': 'cubic-bezier(0.2, 0, 0.38, 0.9)',
    /** Expressive - dramatic, attention-grabbing */
    'motion-easing-expressive': 'cubic-bezier(0.4, 0.14, 0.3, 1)',
    /** Spring - bouncy overshoot for playful feel */
    'motion-easing-spring': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
    /** None animation delay */
    'motion-delay-none': '0ms',
    /** Short animation delay */
    'motion-delay-short': '125ms',
    /** Medium animation delay */
    'motion-delay-medium': '150ms',
    /** Long animation delay */
    'motion-delay-long': '180ms',
    /** Fade from transparent to opaque */
    'motion-keyframe-fade-in': 'from { opacity: 0; } to { opacity: 1; }',
    /** Fade from opaque to transparent */
    'motion-keyframe-fade-out': 'from { opacity: 1; } to { opacity: 0; }',
    /** Slide in from above */
    'motion-keyframe-slide-in-from-top': 'from { transform: translateY(-100%); } to { transform: translateY(0); }',
    /** Slide in from below */
    'motion-keyframe-slide-in-from-bottom': 'from { transform: translateY(100%); } to { transform: translateY(0); }',
    /** Slide in from left */
    'motion-keyframe-slide-in-from-left': 'from { transform: translateX(-100%); } to { transform: translateX(0); }',
    /** Slide in from right */
    'motion-keyframe-slide-in-from-right': 'from { transform: translateX(100%); } to { transform: translateX(0); }',
    /** Slide out upward */
    'motion-keyframe-slide-out-to-top': 'from { transform: translateY(0); } to { transform: translateY(-100%); }',
    /** Slide out downward */
    'motion-keyframe-slide-out-to-bottom': 'from { transform: translateY(0); } to { transform: translateY(100%); }',
    /** Slide out to left */
    'motion-keyframe-slide-out-to-left': 'from { transform: translateX(0); } to { transform: translateX(-100%); }',
    /** Slide out to right */
    'motion-keyframe-slide-out-to-right': 'from { transform: translateX(0); } to { transform: translateX(100%); }',
    /** Scale up while fading in */
    'motion-keyframe-scale-in': 'from { transform: scale(0.96); opacity: 0; } to { transform: scale(1); opacity: 1; }',
    /** Scale down while fading out */
    'motion-keyframe-scale-out': 'from { transform: scale(1); opacity: 1; } to { transform: scale(0.96); opacity: 0; }',
    /** Continuous rotation */
    'motion-keyframe-spin': 'from { transform: rotate(0deg); } to { transform: rotate(360deg); }',
    /** Expanding pulse that fades out */
    'motion-keyframe-ping': '75%, 100% { transform: scale(1.7); opacity: 0; }',
    /** Gentle opacity pulse */
    'motion-keyframe-pulse': '0%, 100% { opacity: 1; } 50% { opacity: 0.48; }',
    /** Bouncing motion */
    'motion-keyframe-bounce': '0%, 100% { transform: translateY(-33%); animation-timing-function: cubic-bezier(0.8, 0, 1, 1); } 50% { transform: translateY(0); animation-timing-function: cubic-bezier(0, 0, 0.2, 1); }',
    /** Expand accordion content */
    'motion-keyframe-accordion-down': 'from { height: 0; } to { height: var(--radix-accordion-content-height); }',
    /** Collapse accordion content */
    'motion-keyframe-accordion-up': 'from { height: var(--radix-accordion-content-height); } to { height: 0; }',
    /** Text cursor blinking */
    'motion-keyframe-caret-blink': '0%, 70%, 100% { opacity: 1; } 20%, 50% { opacity: 0; }',
    /** Fade in animation */
    'motion-animation-fade-in': 'fade-in var(--motion-duration-fast) var(--motion-easing-ease-out)',
    /** Fade out animation */
    'motion-animation-fade-out': 'fade-out var(--motion-duration-fast) var(--motion-easing-ease-in)',
    /** Slide in from top */
    'motion-animation-slide-in-from-top': 'slide-in-from-top var(--motion-duration-normal) var(--motion-easing-ease-out)',
    /** Slide in from bottom */
    'motion-animation-slide-in-from-bottom': 'slide-in-from-bottom var(--motion-duration-normal) var(--motion-easing-ease-out)',
    /** Slide in from left */
    'motion-animation-slide-in-from-left': 'slide-in-from-left var(--motion-duration-normal) var(--motion-easing-ease-out)',
    /** Slide in from right */
    'motion-animation-slide-in-from-right': 'slide-in-from-right var(--motion-duration-normal) var(--motion-easing-ease-out)',
    /** Slide out to top */
    'motion-animation-slide-out-to-top': 'slide-out-to-top var(--motion-duration-fast) var(--motion-easing-ease-in)',
    /** Slide out to bottom */
    'motion-animation-slide-out-to-bottom': 'slide-out-to-bottom var(--motion-duration-fast) var(--motion-easing-ease-in)',
    /** Slide out to left */
    'motion-animation-slide-out-to-left': 'slide-out-to-left var(--motion-duration-fast) var(--motion-easing-ease-in)',
    /** Slide out to right */
    'motion-animation-slide-out-to-right': 'slide-out-to-right var(--motion-duration-fast) var(--motion-easing-ease-in)',
    /** Scale in with spring */
    'motion-animation-scale-in': 'scale-in var(--motion-duration-normal) var(--motion-easing-spring)',
    /** Scale out */
    'motion-animation-scale-out': 'scale-out var(--motion-duration-fast) var(--motion-easing-ease-in)',
    /** Continuous spin */
    'motion-animation-spin': 'spin 1s var(--motion-easing-linear) infinite',
    /** Pinging pulse */
    'motion-animation-ping': 'ping 1s var(--motion-easing-ease-out) infinite',
    /** Gentle pulse */
    'motion-animation-pulse': 'pulse 2s var(--motion-easing-ease-in-out) infinite',
    /** Bouncing */
    'motion-animation-bounce': 'bounce 1s var(--motion-easing-ease-in-out) infinite',
    /** Accordion expand */
    'motion-animation-accordion-down': 'accordion-down var(--motion-duration-normal) var(--motion-easing-ease-out)',
    /** Accordion collapse */
    'motion-animation-accordion-up': 'accordion-up var(--motion-duration-normal) var(--motion-easing-ease-out)',
    /** Caret blinking */
    'motion-animation-caret-blink': 'caret-blink 1.25s var(--motion-easing-ease-out) infinite',
    /** Fade in animation preset */
    'motion-fade-in': '125ms cubic-bezier(0, 0, 0.58, 1)',
    /** Fade out animation preset */
    'motion-fade-out': '125ms cubic-bezier(0.42, 0, 1, 1)',
    /** Slide in animation preset */
    'motion-slide-in': '150ms cubic-bezier(0, 0, 0.58, 1)',
    /** Slide out animation preset */
    'motion-slide-out': '125ms cubic-bezier(0.42, 0, 1, 1)',
    /** Scale in with spring animation */
    'motion-scale-in': '150ms cubic-bezier(0.175, 0.885, 0.32, 1.275)',
    /** Metadata about the motion progression system */
    'motion-progression': {"ratio":"minor-third","ratioValue":1.2,"baseDuration":150,"note":"Motion timing uses step-based progression (base * ratio^step) for unified feel"},
  },
  radius: {
    /** Base border radius - all other radii derive from this value */
    'radius-base': '0.375rem',
    /** No border radius - sharp corners */
    'radius-none': '0',
    /** Small radius for subtle rounding */
    'radius-sm': '0.31rem',
    /** Default radius - primary UI elements */
    'radius': '0.38rem',
    /** Medium radius for containers */
    'radius-md': '0.45rem',
    /** Large radius for prominent containers */
    'radius-lg': '0.54rem',
    /** Extra large radius for emphasized elements */
    'radius-xl': '0.65rem',
    /** Maximum meaningful radius */
    'radius-2xl': '0.78rem',
    /** Very large radius for special cases */
    'radius-3xl': '0.93rem',
    /** Fully rounded - circles and pills */
    'radius-full': '9999px',
  },
  semantic: {
    /** Primary page background color */
    'background': 'var(--color-neutral-50)',
    /** Primary text color */
    'foreground': 'var(--color-neutral-950)',
    /** Card and contained surface background */
    'card': 'var(--color-neutral-50)',
    /** Text on card surfaces */
    'card-foreground': 'var(--color-neutral-950)',
    /** Card hover state background */
    'card-hover': 'var(--color-neutral-100)',
    /** Card border color */
    'card-border': 'var(--color-neutral-200)',
    /** Popover and dropdown background */
    'popover': 'var(--color-neutral-50)',
    /** Text in popovers */
    'popover-foreground': 'var(--color-neutral-950)',
    /** Popover border color */
    'popover-border': 'var(--color-neutral-200)',
    /** Elevated surface background */
    'surface': 'var(--color-neutral-50)',
    /** Text on surface backgrounds */
    'surface-foreground': 'var(--color-neutral-950)',
    /** Surface hover state */
    'surface-hover': 'var(--color-neutral-100)',
    /** Surface active/pressed state */
    'surface-active': 'var(--color-neutral-200)',
    /** Surface border color */
    'surface-border': 'var(--color-neutral-200)',
    /** Primary interactive elements - buttons, links, focus states */
    'primary': 'var(--color-neutral-900)',
    /** Text on primary color backgrounds */
    'primary-foreground': 'var(--color-neutral-50)',
    /** Primary hover state */
    'primary-hover': 'var(--color-neutral-800)',
    /** Text on primary hover */
    'primary-hover-foreground': 'var(--color-neutral-50)',
    /** Primary active/pressed state */
    'primary-active': 'var(--color-neutral-700)',
    /** Text on primary active */
    'primary-active-foreground': 'var(--color-neutral-50)',
    /** Primary focus state */
    'primary-focus': 'var(--color-neutral-900)',
    /** Primary border color */
    'primary-border': 'var(--color-neutral-900)',
    /** Primary focus ring color */
    'primary-ring': 'var(--color-neutral-900)',
    /** Subtle primary background for badges/alerts */
    'primary-subtle': 'var(--color-neutral-100)',
    /** Text on subtle primary backgrounds */
    'primary-subtle-foreground': 'var(--color-neutral-900)',
    /** Secondary interactive elements - less prominent actions */
    'secondary': 'var(--color-neutral-100)',
    /** Text on secondary color backgrounds */
    'secondary-foreground': 'var(--color-neutral-900)',
    /** Secondary hover state */
    'secondary-hover': 'var(--color-neutral-200)',
    /** Text on secondary hover */
    'secondary-hover-foreground': 'var(--color-neutral-900)',
    /** Secondary active/pressed state */
    'secondary-active': 'var(--color-neutral-300)',
    /** Text on secondary active */
    'secondary-active-foreground': 'var(--color-neutral-900)',
    /** Secondary focus state */
    'secondary-focus': 'var(--color-neutral-100)',
    /** Secondary border color */
    'secondary-border': 'var(--color-neutral-300)',
    /** Secondary focus ring color */
    'secondary-ring': 'var(--color-neutral-400)',
    /** Muted backgrounds for subtle emphasis */
    'muted': 'var(--color-neutral-100)',
    /** Muted text for secondary information */
    'muted-foreground': 'var(--color-neutral-500)',
    /** Muted hover state */
    'muted-hover': 'var(--color-neutral-200)',
    /** Text on muted hover */
    'muted-hover-foreground': 'var(--color-neutral-600)',
    /** Muted active state */
    'muted-active': 'var(--color-neutral-300)',
    /** Muted border color */
    'muted-border': 'var(--color-neutral-200)',
    /** Accent for hover states and highlights */
    'accent': 'var(--color-neutral-100)',
    /** Text on accent backgrounds */
    'accent-foreground': 'var(--color-neutral-900)',
    /** Accent hover state */
    'accent-hover': 'var(--color-neutral-200)',
    /** Text on accent hover */
    'accent-hover-foreground': 'var(--color-neutral-900)',
    /** Accent active state */
    'accent-active': 'var(--color-neutral-300)',
    /** Text on accent active */
    'accent-active-foreground': 'var(--color-neutral-900)',
    /** Accent border color */
    'accent-border': 'var(--color-neutral-300)',
    /** Accent focus ring color */
    'accent-ring': 'var(--color-neutral-400)',
    /** Destructive actions - delete, remove, critical warnings */
    'destructive': 'var(--color-silver-bold-fire-truck-600)',
    /** Text on destructive backgrounds */
    'destructive-foreground': 'var(--color-neutral-50)',
    /** Destructive hover state */
    'destructive-hover': 'var(--color-silver-bold-fire-truck-700)',
    /** Text on destructive hover */
    'destructive-hover-foreground': 'var(--color-neutral-50)',
    /** Destructive active/pressed state */
    'destructive-active': 'var(--color-silver-bold-fire-truck-800)',
    /** Text on destructive active */
    'destructive-active-foreground': 'var(--color-neutral-50)',
    /** Destructive focus state */
    'destructive-focus': 'var(--color-silver-bold-fire-truck-600)',
    /** Destructive border color */
    'destructive-border': 'var(--color-silver-bold-fire-truck-600)',
    /** Destructive focus ring color */
    'destructive-ring': 'var(--color-silver-bold-fire-truck-600)',
    /** Subtle destructive background for error alerts */
    'destructive-subtle': 'var(--color-silver-bold-fire-truck-50)',
    /** Text on subtle destructive backgrounds */
    'destructive-subtle-foreground': 'var(--color-silver-bold-fire-truck-700)',
    /** Success states - confirmations, completions, positive feedback */
    'success': 'var(--color-silver-true-citrine-600)',
    /** Text on success backgrounds */
    'success-foreground': 'var(--color-neutral-50)',
    /** Success hover state */
    'success-hover': 'var(--color-silver-true-citrine-700)',
    /** Text on success hover */
    'success-hover-foreground': 'var(--color-neutral-50)',
    /** Success active/pressed state */
    'success-active': 'var(--color-silver-true-citrine-800)',
    /** Text on success active */
    'success-active-foreground': 'var(--color-neutral-50)',
    /** Success focus state */
    'success-focus': 'var(--color-silver-true-citrine-600)',
    /** Success border color */
    'success-border': 'var(--color-silver-true-citrine-600)',
    /** Success focus ring color */
    'success-ring': 'var(--color-silver-true-citrine-600)',
    /** Subtle success background for success alerts */
    'success-subtle': 'var(--color-silver-true-citrine-50)',
    /** Text on subtle success backgrounds */
    'success-subtle-foreground': 'var(--color-silver-true-citrine-700)',
    /** Warning states - caution, potential issues, important notices */
    'warning': 'var(--color-silver-true-honey-500)',
    /** Text on warning backgrounds */
    'warning-foreground': 'var(--color-neutral-950)',
    /** Warning hover state */
    'warning-hover': 'var(--color-silver-true-honey-600)',
    /** Text on warning hover */
    'warning-hover-foreground': 'var(--color-neutral-950)',
    /** Warning active/pressed state */
    'warning-active': 'var(--color-silver-true-honey-700)',
    /** Text on warning active */
    'warning-active-foreground': 'var(--color-neutral-50)',
    /** Warning focus state */
    'warning-focus': 'var(--color-silver-true-honey-500)',
    /** Warning border color */
    'warning-border': 'var(--color-silver-true-honey-500)',
    /** Warning focus ring color */
    'warning-ring': 'var(--color-silver-true-honey-600)',
    /** Subtle warning background for warning alerts */
    'warning-subtle': 'var(--color-silver-true-honey-50)',
    /** Text on subtle warning backgrounds */
    'warning-subtle-foreground': 'var(--color-silver-true-honey-800)',
    /** Informational states - tips, help, neutral information */
    'info': 'var(--color-silver-true-sky-600)',
    /** Text on info backgrounds */
    'info-foreground': 'var(--color-neutral-50)',
    /** Info hover state */
    'info-hover': 'var(--color-silver-true-sky-700)',
    /** Text on info hover */
    'info-hover-foreground': 'var(--color-neutral-50)',
    /** Info active/pressed state */
    'info-active': 'var(--color-silver-true-sky-800)',
    /** Text on info active */
    'info-active-foreground': 'var(--color-neutral-50)',
    /** Info focus state */
    'info-focus': 'var(--color-silver-true-sky-600)',
    /** Info border color */
    'info-border': 'var(--color-silver-true-sky-600)',
    /** Info focus ring color */
    'info-ring': 'var(--color-silver-true-sky-600)',
    /** Subtle info background for info alerts */
    'info-subtle': 'var(--color-silver-true-sky-50)',
    /** Text on subtle info backgrounds */
    'info-subtle-foreground': 'var(--color-silver-true-sky-700)',
    /** Critical alert states */
    'alert': 'var(--color-silver-bold-fire-truck-600)',
    /** Text on alert backgrounds */
    'alert-foreground': 'var(--color-neutral-50)',
    /** Alert hover state */
    'alert-hover': 'var(--color-silver-bold-fire-truck-700)',
    /** Text on alert hover */
    'alert-hover-foreground': 'var(--color-neutral-50)',
    /** Alert active state */
    'alert-active': 'var(--color-silver-bold-fire-truck-800)',
    /** Text on alert active */
    'alert-active-foreground': 'var(--color-neutral-50)',
    /** Alert border color */
    'alert-border': 'var(--color-silver-bold-fire-truck-600)',
    /** Alert focus ring color */
    'alert-ring': 'var(--color-silver-bold-fire-truck-600)',
    /** Subtle alert background */
    'alert-subtle': 'var(--color-silver-bold-fire-truck-50)',
    /** Text on subtle alert backgrounds */
    'alert-subtle-foreground': 'var(--color-silver-bold-fire-truck-700)',
    /** Highlight for search results, selected text, emphasis */
    'highlight': 'var(--color-silver-true-violet-200)',
    /** Text on highlight backgrounds */
    'highlight-foreground': 'var(--color-silver-true-violet-900)',
    /** Highlight hover state */
    'highlight-hover': 'var(--color-silver-true-violet-300)',
    /** Text on highlight hover */
    'highlight-hover-foreground': 'var(--color-silver-true-violet-900)',
    /** Highlight active state */
    'highlight-active': 'var(--color-silver-true-violet-400)',
    /** Text on highlight active */
    'highlight-active-foreground': 'var(--color-silver-true-violet-950)',
    /** Default border color */
    'border': 'var(--color-neutral-200)',
    /** Border hover state */
    'border-hover': 'var(--color-neutral-300)',
    /** Border focus state */
    'border-focus': 'var(--color-neutral-400)',
    /** Border active state */
    'border-active': 'var(--color-neutral-500)',
    /** Input field border color */
    'input': 'var(--color-neutral-200)',
    /** Input text color */
    'input-foreground': 'var(--color-neutral-950)',
    /** Input hover state */
    'input-hover': 'var(--color-neutral-300)',
    /** Input focus state */
    'input-focus': 'var(--color-neutral-400)',
    /** Disabled input background */
    'input-disabled': 'var(--color-neutral-100)',
    /** Disabled input text color */
    'input-disabled-foreground': 'var(--color-neutral-400)',
    /** Placeholder text color */
    'input-placeholder': 'var(--color-neutral-500)',
    /** Invalid input border */
    'input-invalid': 'var(--color-silver-bold-fire-truck-500)',
    /** Invalid input error text */
    'input-invalid-foreground': 'var(--color-silver-bold-fire-truck-700)',
    /** Valid input border */
    'input-valid': 'var(--color-silver-true-citrine-500)',
    /** Valid input success text */
    'input-valid-foreground': 'var(--color-silver-true-citrine-700)',
    /** Focus ring color */
    'ring': 'var(--color-neutral-950)',
    /** Focus ring offset color */
    'ring-offset': 'var(--color-neutral-50)',
    /** Primary focus ring */
    'ring-primary': 'var(--color-neutral-900)',
    /** Destructive focus ring */
    'ring-destructive': 'var(--color-silver-bold-fire-truck-600)',
    /** Success focus ring */
    'ring-success': 'var(--color-silver-true-citrine-600)',
    /** Warning focus ring */
    'ring-warning': 'var(--color-silver-true-honey-600)',
    /** Info focus ring */
    'ring-info': 'var(--color-silver-true-sky-600)',
    /** Link color */
    'link': 'var(--color-silver-true-sky-700)',
    /** Link hover color */
    'link-hover': 'var(--color-silver-true-sky-800)',
    /** Link active/pressed color */
    'link-active': 'var(--color-silver-true-sky-900)',
    /** Visited link color */
    'link-visited': 'var(--color-silver-true-violet-700)',
    /** Link focus color */
    'link-focus': 'var(--color-silver-true-sky-700)',
    /** Text selection background */
    'selection': 'var(--color-silver-true-sky-200)',
    /** Text selection foreground */
    'selection-foreground': 'var(--color-neutral-950)',
    /** Sidebar background */
    'sidebar': 'var(--color-neutral-50)',
    /** Sidebar text color */
    'sidebar-foreground': 'var(--color-neutral-950)',
    /** Sidebar muted text */
    'sidebar-muted': 'var(--color-neutral-500)',
    /** Sidebar primary accent */
    'sidebar-primary': 'var(--color-neutral-900)',
    /** Text on sidebar primary */
    'sidebar-primary-foreground': 'var(--color-neutral-50)',
    /** Sidebar primary hover */
    'sidebar-primary-hover': 'var(--color-neutral-800)',
    /** Sidebar primary active */
    'sidebar-primary-active': 'var(--color-neutral-700)',
    /** Sidebar hover/accent state */
    'sidebar-accent': 'var(--color-neutral-100)',
    /** Text on sidebar accent */
    'sidebar-accent-foreground': 'var(--color-neutral-900)',
    /** Sidebar accent hover */
    'sidebar-accent-hover': 'var(--color-neutral-200)',
    /** Sidebar accent active */
    'sidebar-accent-active': 'var(--color-neutral-300)',
    /** Sidebar item background */
    'sidebar-item': 'var(--color-neutral-50)',
    /** Sidebar item text */
    'sidebar-item-foreground': 'var(--color-neutral-700)',
    /** Sidebar item hover */
    'sidebar-item-hover': 'var(--color-neutral-100)',
    /** Sidebar item hover text */
    'sidebar-item-hover-foreground': 'var(--color-neutral-900)',
    /** Sidebar item active */
    'sidebar-item-active': 'var(--color-neutral-200)',
    /** Sidebar item active text */
    'sidebar-item-active-foreground': 'var(--color-neutral-950)',
    /** Sidebar selected item */
    'sidebar-item-selected': 'var(--color-neutral-100)',
    /** Sidebar selected item text */
    'sidebar-item-selected-foreground': 'var(--color-neutral-950)',
    /** Sidebar border/divider color */
    'sidebar-border': 'var(--color-neutral-200)',
    /** Sidebar focus ring */
    'sidebar-ring': 'var(--color-neutral-950)',
    /** Navigation background */
    'nav': 'var(--color-neutral-50)',
    /** Navigation text */
    'nav-foreground': 'var(--color-neutral-700)',
    /** Navigation hover */
    'nav-hover': 'var(--color-neutral-100)',
    /** Navigation hover text */
    'nav-hover-foreground': 'var(--color-neutral-900)',
    /** Navigation active */
    'nav-active': 'var(--color-neutral-200)',
    /** Navigation active text */
    'nav-active-foreground': 'var(--color-neutral-950)',
    /** Navigation selected */
    'nav-selected': 'var(--color-neutral-900)',
    /** Navigation selected text */
    'nav-selected-foreground': 'var(--color-neutral-50)',
    /** Navigation disabled */
    'nav-disabled': 'var(--color-neutral-200)',
    /** Navigation disabled text */
    'nav-disabled-foreground': 'var(--color-neutral-400)',
    /** Table background */
    'table': 'var(--color-neutral-50)',
    /** Table text */
    'table-foreground': 'var(--color-neutral-950)',
    /** Table header background */
    'table-header': 'var(--color-neutral-100)',
    /** Table header text */
    'table-header-foreground': 'var(--color-neutral-950)',
    /** Table row hover */
    'table-row-hover': 'var(--color-neutral-50)',
    /** Table row selected */
    'table-row-selected': 'var(--color-neutral-100)',
    /** Table row selected text */
    'table-row-selected-foreground': 'var(--color-neutral-950)',
    /** Table border */
    'table-border': 'var(--color-neutral-200)',
    /** Tooltip background */
    'tooltip': 'var(--color-neutral-900)',
    /** Tooltip text */
    'tooltip-foreground': 'var(--color-neutral-50)',
    /** Overlay background */
    'overlay': 'var(--color-neutral-950)',
    /** Overlay text */
    'overlay-foreground': 'var(--color-neutral-50)',
    /** Skeleton loader background */
    'skeleton': 'var(--color-neutral-200)',
    /** Skeleton loader highlight */
    'skeleton-highlight': 'var(--color-neutral-300)',
    /** Primary chart color */
    'chart-1': 'var(--color-silver-true-glacier-500)',
    /** Secondary chart color */
    'chart-2': 'var(--color-silver-true-sky-500)',
    /** Tertiary chart color */
    'chart-3': 'var(--color-silver-true-citrine-500)',
    /** Quaternary chart color */
    'chart-4': 'var(--color-silver-true-honey-500)',
    /** Quinary chart color */
    'chart-5': 'var(--color-silver-true-violet-500)',
    /** Scrollbar thumb color */
    'scrollbar': 'var(--color-neutral-300)',
    /** Scrollbar thumb hover */
    'scrollbar-hover': 'var(--color-neutral-400)',
    /** Scrollbar track background */
    'scrollbar-track': 'var(--color-neutral-100)',
    /** Code block background */
    'code': 'var(--color-neutral-100)',
    /** Code text color */
    'code-foreground': 'var(--color-neutral-900)',
    /** Code block border */
    'code-border': 'var(--color-neutral-200)',
    /** Badge background */
    'badge': 'var(--color-neutral-100)',
    /** Badge text color */
    'badge-foreground': 'var(--color-neutral-900)',
    /** Badge border */
    'badge-border': 'var(--color-neutral-200)',
    /** Avatar fallback background */
    'avatar': 'var(--color-neutral-200)',
    /** Avatar fallback text/icon color */
    'avatar-foreground': 'var(--color-neutral-600)',
  },
  shadow: {
    /** Base unit for shadow calculations - tied to spacing for consistency */
    'shadow-base-unit': '0.25rem',
    /** No shadow - flat appearance */
    'shadow-none': 'none',
    /** Extra small shadow - subtle depth hint */
    'shadow-xs': '0 0.063rem 0.125rem 0rem rgb(0 0 0 / 0.05)',
    /** Small shadow - slight elevation */
    'shadow-sm': '0 0.063rem 0.25rem 0rem rgb(0 0 0 / 0.06), 0 0.063rem 0.125rem 0rem rgb(0 0 0 / 0.1)',
    /** Default shadow - standard elevation */
    'shadow': '0 0.125rem 0.375rem -0.062rem rgb(0 0 0 / 0.1), 0 0.063rem 0.125rem 0rem rgb(0 0 0 / 0.1)',
    /** Medium shadow - noticeable elevation */
    'shadow-md': '0 0.25rem 0.5rem -0.125rem rgb(0 0 0 / 0.1), 0 0.125rem 0.25rem -0.062rem rgb(0 0 0 / 0.1)',
    /** Large shadow - significant elevation */
    'shadow-lg': '0 0.5rem 1rem -0.187rem rgb(0 0 0 / 0.1), 0 0.25rem 0.5rem -0.125rem rgb(0 0 0 / 0.1)',
    /** Extra large shadow - high elevation */
    'shadow-xl': '0 1.25rem 1.5rem -0.25rem rgb(0 0 0 / 0.1), 0 0.5rem 1rem -0.187rem rgb(0 0 0 / 0.1)',
    /** Maximum shadow - highest elevation */
    'shadow-2xl': '0 1.5rem 3rem -0.5rem rgb(0 0 0 / 0.25)',
    /** Primary colored shadow for emphasis */
    'shadow-primary': '0 0.125rem 0.375rem -0.062rem color-mix(in oklch, var(--primary) 12%, transparent)',
    /** Destructive colored shadow for warnings */
    'shadow-destructive': '0 0.125rem 0.375rem -0.062rem color-mix(in oklch, var(--destructive) 12%, transparent)',
    /** Metadata about the shadow progression system */
    'shadow-progression': {"ratio":"minor-third","ratioValue":1.2,"baseUnit":4,"note":"Shadow values derived from spacing progression for visual harmony"},
  },
  spacing: {
    /** Foundation spacing unit - all spacing derives from this value */
    'spacing-base': '0.25rem',
    /** Zero spacing - remove all spacing */
    'spacing-0': '0',
    /** Micro spacing for tight layouts and inline elements */
    'spacing-0.5': '0.125rem',
    /** Micro spacing for tight layouts and inline elements */
    'spacing-1': '0.25rem',
    /** Small spacing for component internals and related elements */
    'spacing-1.5': '0.375rem',
    /** Small spacing for component internals and related elements */
    'spacing-2': '0.5rem',
    /** Small spacing for component internals and related elements */
    'spacing-2.5': '0.625rem',
    /** Small spacing for component internals and related elements */
    'spacing-3': '0.75rem',
    /** Small spacing for component internals and related elements */
    'spacing-3.5': '0.875rem',
    /** Small spacing for component internals and related elements */
    'spacing-4': '1rem',
    /** Medium spacing for section separation and breathing room */
    'spacing-5': '1.25rem',
    /** Medium spacing for section separation and breathing room */
    'spacing-6': '1.5rem',
    /** Medium spacing for section separation and breathing room */
    'spacing-7': '1.75rem',
    /** Medium spacing for section separation and breathing room */
    'spacing-8': '2rem',
    /** Medium spacing for section separation and breathing room */
    'spacing-9': '2.25rem',
    /** Medium spacing for section separation and breathing room */
    'spacing-10': '2.5rem',
    /** Medium spacing for section separation and breathing room */
    'spacing-11': '2.75rem',
    /** Medium spacing for section separation and breathing room */
    'spacing-12': '3rem',
    /** Large spacing for major section breaks and layout gaps */
    'spacing-14': '3.5rem',
    /** Large spacing for major section breaks and layout gaps */
    'spacing-16': '4rem',
    /** Large spacing for major section breaks and layout gaps */
    'spacing-20': '5rem',
    /** Large spacing for major section breaks and layout gaps */
    'spacing-24': '6rem',
    /** Large spacing for major section breaks and layout gaps */
    'spacing-28': '7rem',
    /** Large spacing for major section breaks and layout gaps */
    'spacing-32': '8rem',
    /** Extra large spacing for page-level layout and hero sections */
    'spacing-36': '9rem',
    /** Extra large spacing for page-level layout and hero sections */
    'spacing-40': '10rem',
    /** Extra large spacing for page-level layout and hero sections */
    'spacing-44': '11rem',
    /** Extra large spacing for page-level layout and hero sections */
    'spacing-48': '12rem',
    /** Extra large spacing for page-level layout and hero sections */
    'spacing-52': '13rem',
    /** Extra large spacing for page-level layout and hero sections */
    'spacing-56': '14rem',
    /** Extra large spacing for page-level layout and hero sections */
    'spacing-60': '15rem',
    /** Extra large spacing for page-level layout and hero sections */
    'spacing-64': '16rem',
    /** Extra large spacing for page-level layout and hero sections */
    'spacing-72': '18rem',
    /** Extra large spacing for page-level layout and hero sections */
    'spacing-80': '20rem',
    /** Extra large spacing for page-level layout and hero sections */
    'spacing-96': '24rem',
    /** Metadata about the spacing progression system */
    'spacing-progression': {"ratio":"minor-third","ratioValue":1.2,"baseUnit":4,"sample":[0,4,4.8,5.76,6.91,8.29,9.95,11.94,14.33,17.2]},
  },
  typography: {
    /** Primary font family for UI text */
    'font-sans': "'Noto Sans Variable', sans-serif",
    /** Monospace font family for code */
    'font-mono': "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace",
    /** Body text range for primary content */
    'font-size-base': '1rem',
    /** Small text for captions, labels, and secondary information */
    'font-size-xs': '0.694rem',
    /** Line height for xs text size */
    'line-height-xs': '1.5',
    /** Letter spacing for xs text size */
    'letter-spacing-xs': '0.025em',
    /** Small text for captions, labels, and secondary information */
    'font-size-sm': '0.833rem',
    /** Line height for sm text size */
    'line-height-sm': '1.5',
    /** Letter spacing for sm text size */
    'letter-spacing-sm': '0.015em',
    /** Line height for base text size */
    'line-height-base': '1.5',
    /** Letter spacing for base text size */
    'letter-spacing-base': '0',
    /** Body text range for primary content */
    'font-size-lg': '1.2rem',
    /** Line height for lg text size */
    'line-height-lg': '1.5',
    /** Letter spacing for lg text size */
    'letter-spacing-lg': '-0.01em',
    /** Heading text for section titles */
    'font-size-xl': '1.44rem',
    /** Line height for xl text size */
    'line-height-xl': '1.4',
    /** Letter spacing for xl text size */
    'letter-spacing-xl': '-0.015em',
    /** Heading text for section titles */
    'font-size-2xl': '1.728rem',
    /** Line height for 2xl text size */
    'line-height-2xl': '1.35',
    /** Letter spacing for 2xl text size */
    'letter-spacing-2xl': '-0.02em',
    /** Heading text for section titles */
    'font-size-3xl': '2.074rem',
    /** Line height for 3xl text size */
    'line-height-3xl': '1.3',
    /** Letter spacing for 3xl text size */
    'letter-spacing-3xl': '-0.025em',
    /** Display text for hero sections and major headings */
    'font-size-4xl': '2.488rem',
    /** Line height for 4xl text size */
    'line-height-4xl': '1.25',
    /** Letter spacing for 4xl text size */
    'letter-spacing-4xl': '-0.03em',
    /** Display text for hero sections and major headings */
    'font-size-5xl': '2.986rem',
    /** Line height for 5xl text size */
    'line-height-5xl': '1.2',
    /** Letter spacing for 5xl text size */
    'letter-spacing-5xl': '-0.035em',
    /** Display text for hero sections and major headings */
    'font-size-6xl': '3.583rem',
    /** Line height for 6xl text size */
    'line-height-6xl': '1.15',
    /** Letter spacing for 6xl text size */
    'letter-spacing-6xl': '-0.04em',
    /** Display text for hero sections and major headings */
    'font-size-7xl': '4.3rem',
    /** Line height for 7xl text size */
    'line-height-7xl': '1.1',
    /** Letter spacing for 7xl text size */
    'letter-spacing-7xl': '-0.045em',
    /** Display text for hero sections and major headings */
    'font-size-8xl': '5.16rem',
    /** Line height for 8xl text size */
    'line-height-8xl': '1.1',
    /** Letter spacing for 8xl text size */
    'letter-spacing-8xl': '-0.05em',
    /** Display text for hero sections and major headings */
    'font-size-9xl': '6.192rem',
    /** Line height for 9xl text size */
    'line-height-9xl': '1.1',
    /** Letter spacing for 9xl text size */
    'letter-spacing-9xl': '-0.05em',
    /** Thin weight */
    'font-weight-thin': '100',
    /** Extra light weight */
    'font-weight-extralight': '200',
    /** Light weight */
    'font-weight-light': '300',
    /** Normal weight */
    'font-weight-normal': '400',
    /** Medium weight */
    'font-weight-medium': '500',
    /** Semibold weight */
    'font-weight-semibold': '600',
    /** Bold weight */
    'font-weight-bold': '700',
    /** Extra bold weight */
    'font-weight-extrabold': '800',
    /** Black weight */
    'font-weight-black': '900',
    /** Metadata about the typography progression system */
    'typography-progression': {"ratio":"minor-third","ratioValue":1.2,"baseFontSize":16,"scale":{"xs":11.11,"sm":13.33,"base":16,"lg":19.2,"xl":23.04,"2xl":27.65,"3xl":33.18,"4xl":39.81,"5xl":47.78,"6xl":57.33,"7xl":68.8,"8xl":82.56,"9xl":99.07}},
  },
} as const;

export type TokenNamespace = keyof typeof tokens;

export type BreakpointToken = keyof typeof tokens.breakpoint;
export type ColorToken = keyof typeof tokens.color;
export type DepthToken = keyof typeof tokens.depth;
export type ElevationToken = keyof typeof tokens.elevation;
export type FocusToken = keyof typeof tokens.focus;
export type MotionToken = keyof typeof tokens.motion;
export type RadiusToken = keyof typeof tokens.radius;
export type SemanticToken = keyof typeof tokens.semantic;
export type ShadowToken = keyof typeof tokens.shadow;
export type SpacingToken = keyof typeof tokens.spacing;
export type TypographyToken = keyof typeof tokens.typography;

export type TokenName =
  | BreakpointToken
  | ColorToken
  | DepthToken
  | ElevationToken
  | FocusToken
  | MotionToken
  | RadiusToken
  | SemanticToken
  | ShadowToken
  | SpacingToken
  | TypographyToken;

/** Get a token value by namespace and name */
export function getToken<N extends TokenNamespace>(
  namespace: N,
  name: keyof typeof tokens[N]
): (typeof tokens)[N][typeof name] {
  return tokens[namespace][name];
}
